/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVenuesRouteImport } from './routes/admin.venues'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminDriverWalletsRouteImport } from './routes/admin.driver-wallets'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminDriversIdRouteImport } from './routes/admin.drivers_.$id'
import { Route as AdminCustomersIdRouteImport } from './routes/admin.customers_.$id'
import { Route as AdminBookingsIdRouteImport } from './routes/admin.bookings_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVenuesRoute = AdminVenuesRouteImport.update({
  id: '/admin/venues',
  path: '/admin/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/admin/promotions',
  path: '/admin/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriverWalletsRoute = AdminDriverWalletsRouteImport.update({
  id: '/admin/driver-wallets',
  path: '/admin/driver-wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversIdRoute = AdminDriversIdRouteImport.update({
  id: '/admin/drivers_/$id',
  path: '/admin/drivers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/admin/customers_/$id',
  path: '/admin/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsIdRoute = AdminBookingsIdRouteImport.update({
  id: '/admin/bookings_/$id',
  path: '/admin/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/driver-wallets': typeof AdminDriverWalletsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/drivers/$id': typeof AdminDriversIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/driver-wallets': typeof AdminDriverWalletsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/drivers/$id': typeof AdminDriversIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/driver-wallets': typeof AdminDriverWalletsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bookings_/$id': typeof AdminBookingsIdRoute
  '/admin/customers_/$id': typeof AdminCustomersIdRoute
  '/admin/drivers_/$id': typeof AdminDriversIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/driver-wallets'
    | '/admin/drivers'
    | '/admin/login'
    | '/admin/payouts'
    | '/admin/pricing'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/support'
    | '/admin/venues'
    | '/admin/'
    | '/admin/bookings/$id'
    | '/admin/customers/$id'
    | '/admin/drivers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/driver-wallets'
    | '/admin/drivers'
    | '/admin/login'
    | '/admin/payouts'
    | '/admin/pricing'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/support'
    | '/admin/venues'
    | '/admin'
    | '/admin/bookings/$id'
    | '/admin/customers/$id'
    | '/admin/drivers/$id'
  id:
    | '__root__'
    | '/'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/driver-wallets'
    | '/admin/drivers'
    | '/admin/login'
    | '/admin/payouts'
    | '/admin/pricing'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/support'
    | '/admin/venues'
    | '/admin/'
    | '/admin/bookings_/$id'
    | '/admin/customers_/$id'
    | '/admin/drivers_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDriverWalletsRoute: typeof AdminDriverWalletsRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminVenuesRoute: typeof AdminVenuesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBookingsIdRoute: typeof AdminBookingsIdRoute
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
  AdminDriversIdRoute: typeof AdminDriversIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/venues': {
      id: '/admin/venues'
      path: '/admin/venues'
      fullPath: '/admin/venues'
      preLoaderRoute: typeof AdminVenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/admin/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/driver-wallets': {
      id: '/admin/driver-wallets'
      path: '/admin/driver-wallets'
      fullPath: '/admin/driver-wallets'
      preLoaderRoute: typeof AdminDriverWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers_/$id': {
      id: '/admin/drivers_/$id'
      path: '/admin/drivers/$id'
      fullPath: '/admin/drivers/$id'
      preLoaderRoute: typeof AdminDriversIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers_/$id': {
      id: '/admin/customers_/$id'
      path: '/admin/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings_/$id': {
      id: '/admin/bookings_/$id'
      path: '/admin/bookings/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AdminBookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDriverWalletsRoute: AdminDriverWalletsRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminVenuesRoute: AdminVenuesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBookingsIdRoute: AdminBookingsIdRoute,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
  AdminDriversIdRoute: AdminDriversIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
