/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DriverProfileRouteImport } from './routes/driver.profile'
import { Route as DriverLoginRouteImport } from './routes/driver.login'
import { Route as DriverEarningsRouteImport } from './routes/driver.earnings'
import { Route as BookingSearchingRouteImport } from './routes/booking_.searching'
import { Route as BookingIdRouteImport } from './routes/booking_.$id'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as DriverTripsIndexRouteImport } from './routes/driver.trips.index'
import { Route as DriverTripsIdRouteImport } from './routes/driver.trips.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/driver/profile',
  path: '/driver/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverLoginRoute = DriverLoginRouteImport.update({
  id: '/driver/login',
  path: '/driver/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/driver/earnings',
  path: '/driver/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSearchingRoute = BookingSearchingRouteImport.update({
  id: '/booking_/searching',
  path: '/booking/searching',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking_/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/admin/promotions',
  path: '/admin/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTripsIndexRoute = DriverTripsIndexRouteImport.update({
  id: '/driver/trips/',
  path: '/driver/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTripsIdRoute = DriverTripsIdRouteImport.update({
  id: '/driver/trips/$id',
  path: '/driver/trips/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/booking': typeof BookingRoute
  '/change-password': typeof ChangePasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/rewards': typeof RewardsRoute
  '/schedule': typeof ScheduleRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trips': typeof TripsRoute
  '/vehicles': typeof VehiclesRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/support': typeof AdminSupportRoute
  '/booking/$id': typeof BookingIdRoute
  '/booking/searching': typeof BookingSearchingRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/profile': typeof DriverProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/driver/trips/$id': typeof DriverTripsIdRoute
  '/driver/trips/': typeof DriverTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/booking': typeof BookingRoute
  '/change-password': typeof ChangePasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/rewards': typeof RewardsRoute
  '/schedule': typeof ScheduleRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trips': typeof TripsRoute
  '/vehicles': typeof VehiclesRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/support': typeof AdminSupportRoute
  '/booking/$id': typeof BookingIdRoute
  '/booking/searching': typeof BookingSearchingRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/profile': typeof DriverProfileRoute
  '/admin': typeof AdminIndexRoute
  '/driver': typeof DriverIndexRoute
  '/driver/trips/$id': typeof DriverTripsIdRoute
  '/driver/trips': typeof DriverTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/booking': typeof BookingRoute
  '/change-password': typeof ChangePasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/rewards': typeof RewardsRoute
  '/schedule': typeof ScheduleRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trips': typeof TripsRoute
  '/vehicles': typeof VehiclesRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/support': typeof AdminSupportRoute
  '/booking_/$id': typeof BookingIdRoute
  '/booking_/searching': typeof BookingSearchingRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/profile': typeof DriverProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/driver/trips/$id': typeof DriverTripsIdRoute
  '/driver/trips/': typeof DriverTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/booking'
    | '/change-password'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/promotions'
    | '/rewards'
    | '/schedule'
    | '/support'
    | '/terms'
    | '/trips'
    | '/vehicles'
    | '/verify-otp'
    | '/wallet'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/login'
    | '/admin/pricing'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/support'
    | '/booking/$id'
    | '/booking/searching'
    | '/driver/earnings'
    | '/driver/login'
    | '/driver/profile'
    | '/admin/'
    | '/driver/'
    | '/driver/trips/$id'
    | '/driver/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/booking'
    | '/change-password'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/promotions'
    | '/rewards'
    | '/schedule'
    | '/support'
    | '/terms'
    | '/trips'
    | '/vehicles'
    | '/verify-otp'
    | '/wallet'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/login'
    | '/admin/pricing'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/support'
    | '/booking/$id'
    | '/booking/searching'
    | '/driver/earnings'
    | '/driver/login'
    | '/driver/profile'
    | '/admin'
    | '/driver'
    | '/driver/trips/$id'
    | '/driver/trips'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/booking'
    | '/change-password'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/promotions'
    | '/rewards'
    | '/schedule'
    | '/support'
    | '/terms'
    | '/trips'
    | '/vehicles'
    | '/verify-otp'
    | '/wallet'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/login'
    | '/admin/pricing'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/support'
    | '/booking_/$id'
    | '/booking_/searching'
    | '/driver/earnings'
    | '/driver/login'
    | '/driver/profile'
    | '/admin/'
    | '/driver/'
    | '/driver/trips/$id'
    | '/driver/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRoute
  BookingRoute: typeof BookingRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  PromotionsRoute: typeof PromotionsRoute
  RewardsRoute: typeof RewardsRoute
  ScheduleRoute: typeof ScheduleRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TripsRoute: typeof TripsRoute
  VehiclesRoute: typeof VehiclesRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  WalletRoute: typeof WalletRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  BookingIdRoute: typeof BookingIdRoute
  BookingSearchingRoute: typeof BookingSearchingRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverLoginRoute: typeof DriverLoginRoute
  DriverProfileRoute: typeof DriverProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DriverIndexRoute: typeof DriverIndexRoute
  DriverTripsIdRoute: typeof DriverTripsIdRoute
  DriverTripsIndexRoute: typeof DriverTripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/driver/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/login': {
      id: '/driver/login'
      path: '/driver/login'
      fullPath: '/driver/login'
      preLoaderRoute: typeof DriverLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/driver/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking_/searching': {
      id: '/booking_/searching'
      path: '/booking/searching'
      fullPath: '/booking/searching'
      preLoaderRoute: typeof BookingSearchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking_/$id': {
      id: '/booking_/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/admin/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/trips/': {
      id: '/driver/trips/'
      path: '/driver/trips'
      fullPath: '/driver/trips/'
      preLoaderRoute: typeof DriverTripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/trips/$id': {
      id: '/driver/trips/$id'
      path: '/driver/trips/$id'
      fullPath: '/driver/trips/$id'
      preLoaderRoute: typeof DriverTripsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRoute,
  BookingRoute: BookingRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  PromotionsRoute: PromotionsRoute,
  RewardsRoute: RewardsRoute,
  ScheduleRoute: ScheduleRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TripsRoute: TripsRoute,
  VehiclesRoute: VehiclesRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  WalletRoute: WalletRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSupportRoute: AdminSupportRoute,
  BookingIdRoute: BookingIdRoute,
  BookingSearchingRoute: BookingSearchingRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverLoginRoute: DriverLoginRoute,
  DriverProfileRoute: DriverProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  DriverIndexRoute: DriverIndexRoute,
  DriverTripsIdRoute: DriverTripsIdRoute,
  DriverTripsIndexRoute: DriverTripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
